Converted to Build API
breadboard-ai/breadboard pull request #2574
Opened 2024-07-19 09:40 UTC by TinaNikou

Fixes #2543

Migrated the Gemini Simple board to the Build syntax.

2024-07-25 16:50 UTC, aomarks requested changes
The `invoke` call could now be replaced with directly importing and instantiating the board (see https://github.com/orgs/breadboard-ai/discussions/2542#discussioncomment-10130566)

2024-07-26 09:06 UTC, TinaNikou commented
> The `invoke` call could now be replaced with directly importing and instantiating the board (see https://github.com/orgs/breadboard-ai/discussions/2542#discussioncomment-10130566)

Gave it a try but getting type errors (I've commented the details in the discussion https://github.com/orgs/breadboard-ai/discussions/2542#discussioncomment-10157711 )

2024-08-13 15:33 UTC, TinaNikou commented
Following the changes from #2791, I ran the board and gave it a test and all seems to be working now, and I've committed the board JSON.

2024-08-15 19:24 UTC, aomarks approved these changes

2024-08-15 19:24 UTC, merged